version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  etl:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
